name: Run eslint with reviewdog

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: reviewdog/action-eslint@v1.33.0
      - uses: actions/setup-node@v4
        with:
          node_version: 22
      - run: npm ci

